#@ load("@ytt:data", "data")
#@ for ns in data.values.namespaces:
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: registry-credentials
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-rule.0: "upsert after upserting registry-credentials"
    kapp.k14s.io/change-rule.1: "delete after deleting app/tap"
spec:
  toNamespace: #@ ns.name
#@ end