#@ load("@ytt:data", "data")
#! This for loop will loop over the namespace list in desired-namespaces.yaml and will create those namespaces.
#! NOTE: if you have another tool like Tanzu Mission Control or some other process that is taking care of creating namespaces for you,
#! and you don’t want namespace provisioner to create the namespaces, you can delete this file from your GitOps install repository.
#@ for ns in data.values.namespaces:
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: #@ ns.name
  annotations:
    kapp.k14s.io/create-strategy: always-replace
secrets:
  - name: registry-credentials
  - name: git-ssh
  - name: cosign-key-pair
imagePullSecrets:
- name: tap-registry
- name: registry-credentials
#@ end